name: lfd
channels:
  - conda-forge
  - defaults
dependencies:
  - openssl=3.0.16
  - pip=25.0
  - python=3.9.21
  - sqlite=3.45.3
  - pip:
    - accelerate==1.6.0
    - annotated-types==0.7.0
    - anyio==4.9.0
    - asgiref==3.8.1
    - attrs==25.3.0
    - backoff==2.2.1
    - bcrypt==4.3.0
    - bitsandbytes==0.45.5
    - build==1.2.2.post1
    - cachetools==5.5.2
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - chroma-hnswlib==0.7.6
    - chromadb==1.0.7
    - click==8.1.8
    - coloredlogs==15.0.1
    - contourpy==1.3.0
    - cycler==0.12.1
    - deprecated==1.2.18
    - distro==1.9.0
    - durationpy==0.9
    - einops==0.8.1
    - exceptiongroup==1.2.2
    - fastapi==0.115.9
    - filelock==3.18.0
    - flatbuffers==25.2.10
    - fonttools==4.57.0
    - fsspec==2025.3.2
    - google-auth==2.39.0
    - googleapis-common-protos==1.70.0
    - grpcio==1.71.0
    - h11==0.16.0
    - httpcore==1.0.9
    - httptools==0.6.4
    - httpx==0.28.1
    - huggingface-hub==0.30.2
    - humanfriendly==10.0
    - idna==3.10
    - ijson==3.3.0
    - importlib-metadata==8.6.1
    - importlib-resources==6.5.2
    - jinja2==3.1.6
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2025.4.1
    - kiwisolver==1.4.7
    - kubernetes==32.0.1
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.9.4
    - mdurl==0.1.2
    - mmh3==5.1.0
    - modelscope==1.25.0
    - monotonic==1.6
    - mpmath==1.3.0
    - networkx==3.2.1
    - numpy==2.0.2
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - oauthlib==3.2.2
    - onnxruntime==1.19.2
    - opentelemetry-api==1.32.1
    - opentelemetry-exporter-otlp-proto-common==1.32.1
    - opentelemetry-exporter-otlp-proto-grpc==1.32.1
    - opentelemetry-instrumentation==0.53b1
    - opentelemetry-instrumentation-asgi==0.53b1
    - opentelemetry-instrumentation-fastapi==0.53b1
    - opentelemetry-proto==1.32.1
    - opentelemetry-sdk==1.32.1
    - opentelemetry-semantic-conventions==0.53b1
    - opentelemetry-util-http==0.53b1
    - orjson==3.10.16
    - overrides==7.7.0
    - packaging==24.2
    - pandas==2.2.3
    - pillow==11.2.1
    - posthog==4.0.0
    - protobuf==5.29.4
    - psutil==7.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pydantic==2.11.3
    - pydantic-core==2.33.1
    - pygments==2.19.1
    - pyparsing==3.2.3
    - pypika==0.48.9
    - pyproject-hooks==1.2.0
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.1.0
    - pytz==2025.2
    - pyyaml==6.0.2
    - referencing==0.36.2
    - regex==2024.11.6
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rich==14.0.0
    - rpds-py==0.24.0
    - rsa==4.9.1
    - safetensors==0.5.3
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - sentence-transformers==4.1.0
    - sentencepiece==0.2.0
    - shellingham==1.5.4
    - six==1.17.0
    - sniffio==1.3.1
    - starlette==0.45.3
    - sympy==1.13.1
    - tenacity==9.1.2
    - threadpoolctl==3.6.0
    - tiktoken==0.9.0
    - tokenizers==0.21.1
    - tomli==2.2.1
    - torch==2.6.0
    - tqdm==4.67.1
    - transformers-stream-generator==0.0.5
    - triton==3.2.0
    - typer==0.15.2
    - typing-extensions==4.13.2
    - typing-inspection==0.4.0
    - tzdata==2025.2
    - urllib3==2.4.0
    - uvicorn==0.34.2
    - uvloop==0.21.0
    - watchfiles==1.0.5
    - websocket-client==1.8.0
    - websockets==15.0.1
    - wrapt==1.17.2
    - zipp==3.21.0
